### ISSUE TITLE
Criar as salas

### ISSUE THREAD

**Issue by syl3n7** [syl3n7/TheEscapee#1]
Criar as salas consiste no level design dos 3 levels que o player vai ter que ultrapassa(resolver) de forma a completar o jogo.
Necessitamos de uma explicacao escrita / baseada em imagens (pictorica) de forma a retratar o que precisamos de fazer para alcancar determinado objetivo, expliquem por escrito aqui nos comentarios deste issue e coloquem o suporte visual tambem nos comentarios.

**Comment by syl3n7** [comment]
https://github.com/syl3n7/TheEscapee/commit/c4acdda028c82a7bf0647b84d068918d2ff7945d

**Comment by Mariana041** [comment]
Nesta primeira sala, o jogador terá que ultrapassar um labirinto, com apenas um caminho até ao final. 
Ideias: ter obstáculos, para dificultar a vida ao jogador. 

> Como buracos que o jogador terá de saltar, se cair o jogo termina; 

> Ter ou não ter um mapa num canto (ideia a decidir);

> Em caminhos sem saída aparecer um "monstro" que vai dizer "não é este o caminho" e frases semelhantes;

> Haver um cronometro para terminar o labirinto, caso chegue ao fim o jogador começa o labirinto no inicio do jogo, contudo o tempo principal (Do jogo em si, tempo este ainda a decidir no final) continua a contar;

**Comment by syl3n7** [comment]
Eix os criterios para as salas

O jogo tem como tema principal “Escape Room”, o que define alguns critérios iniciais:
• A personagem controlada pelo jogador está num ambiente fechado
• O objetivo principal é sair deste ambiente
• Para conseguir sair, a personagem deve conseguir movimentar-se e interagir com elementos do ambiente e resolver alguns “problemas”
São também definidos critérios relativos às funcionalidades a implementar:
• O ambiente fechado deverá ter:
• Duas ou mais zonas principais a serem exploradas
• Obstáculos entre zonas, que podem ser interativos, e podem ser animados
• Uma saída principal, que é desbloqueada após algumas ações do jogador
• A personagem principal deverá:
• Conseguir mover-se em qualquer orientação, controlado com o teclado
• Selecionar objetos interativos, necessários para resolver “problemas”, que podem ser colecionados ou guardados para futuras interações
• A interação da personagem com elementos do jogo pode realizar-se por:
• Proximidade/colisão com o elemento
• Proximidade/colisão em combinação com clique do teclado
• Proximidade/colisão com elemento e aplicação de força (ex., empurrar)
• Haverá personagens “inimigas” que servem também de obstáculos:
• A interação destes inimigos com a personagem pode levar ao fim do jogo (ex., “guarda” que vê e apanha a personagem)
• O jogo terá elementos de interface gráfica:
• um ecrã inicial, de pausa, e de fim de jogo
• alguns elementos de UI relevantes para o jogo (ex., HP, item na mão)

**Comment by syl3n7** [comment]
FEEDBACK de um tester

![image](https://user-images.githubusercontent.com/3891084/164983036-3654a778-0678-4c0e-b410-8066d826fb51.png)
