### ISSUE TITLE
Criar os Puzzles para a sala 1

### ISSUE THREAD

**Issue by syl3n7** [syl3n7/TheEscapee#2]
@Mariana041 responsavel pela Room1

**Comment by Mariana041** [comment]
O labirinto está a ser criado com base nesta imagem. 

![soluçao](https://user-images.githubusercontent.com/100358775/164947847-a9fa5600-bdcd-4268-86c3-0fa32d27736b.png)

**Comment by Mariana041** [comment]
Finalização da estrutura da Maze

![TheEscapee - Room1 - PC, Mac   Linux Standalone - Unity 2020 3 33f1 _DX11_ 24_04_2022 20_26_04](https://user-images.githubusercontent.com/100358775/164993146-1fee8db6-96c6-4bab-8c99-abec5d34021f.png)


![TheEscapee - Room1 - PC, Mac   Linux Standalone - Unity 2020 3 33f1 _DX11_ 24_04_2022 20_26_18](https://user-images.githubusercontent.com/100358775/164993153-2970b87a-69a3-4904-944c-5748065fc963.png)

**Comment by syl3n7** [comment]
Planeado colocar varias salas dentro do maze em ordem ao jogador resolver puzzles para conseguir continuar a resolver o labirinto
