### ISSUE TITLE
Criar um monstro para o level 1

### ISSUE THREAD

**Issue by syl3n7** [syl3n7/TheEscapee#5]

**Comment by Mariana041** [comment]
Este é o monstro que estou a desenvolver. 

![monstro psd @ 33,3% (Artboard 2, RGB_8#) 23_04_2022 23_21_15](https://user-images.githubusercontent.com/100358775/164947915-b4d842a6-4cd9-433e-b728-3a6ae3e0e985.png)

**Comment by syl3n7** [comment]
Didnt use this asset.
